//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditAssessment.Integration.Credit {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Credit.ICreditAssessment")]
    public interface ICreditAssessment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditAssessment/IsOk", ReplyAction="http://tempuri.org/ICreditAssessment/IsOkResponse")]
        bool IsOk(string counterpart);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditAssessmentChannel : CreditAssessment.Integration.Credit.ICreditAssessment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditAssessmentClient : System.ServiceModel.ClientBase<CreditAssessment.Integration.Credit.ICreditAssessment>, CreditAssessment.Integration.Credit.ICreditAssessment {
        
        public CreditAssessmentClient() {
        }
        
        public CreditAssessmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditAssessmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditAssessmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditAssessmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsOk(string counterpart) {
            return base.Channel.IsOk(counterpart);
        }
    }
}
